// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type DirectionalPairScoreClassView struct {
	inner baml.ClassBuilder
}

func (t *DirectionalPairScoreClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DirectionalPairScoreClassView) PropertyUser1() (ClassPropertyView, error) {
	return t.inner.Property("user1")
}

func (t *DirectionalPairScoreClassView) PropertyUser2() (ClassPropertyView, error) {
	return t.inner.Property("user2")
}

func (t *DirectionalPairScoreClassView) PropertyA_to_b() (ClassPropertyView, error) {
	return t.inner.Property("a_to_b")
}

func (t *DirectionalPairScoreClassView) PropertyB_to_a() (ClassPropertyView, error) {
	return t.inner.Property("b_to_a")
}

func (t *DirectionalPairScoreClassView) PropertyReasoning() (ClassPropertyView, error) {
	return t.inner.Property("reasoning")
}

func (t *TypeBuilder) DirectionalPairScore() (*DirectionalPairScoreClassView, error) {
	bld, err := t.inner.Class("DirectionalPairScore")
	if err != nil {
		return nil, err
	}
	return &DirectionalPairScoreClassView{inner: bld}, nil
}

func (t *DirectionalPairScoreClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type IntroductionDraftClassView struct {
	inner baml.ClassBuilder
}

func (t *IntroductionDraftClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *IntroductionDraftClassView) PropertyIntro() (ClassPropertyView, error) {
	return t.inner.Property("intro")
}

func (t *IntroductionDraftClassView) PropertyStarter_topics() (ClassPropertyView, error) {
	return t.inner.Property("starter_topics")
}

func (t *TypeBuilder) IntroductionDraft() (*IntroductionDraftClassView, error) {
	bld, err := t.inner.Class("IntroductionDraft")
	if err != nil {
		return nil, err
	}
	return &IntroductionDraftClassView{inner: bld}, nil
}

func (t *IntroductionDraftClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PairScoringInputClassView struct {
	inner baml.ClassBuilder
}

func (t *PairScoringInputClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PairScoringInputClassView) PropertyUser1() (ClassPropertyView, error) {
	return t.inner.Property("user1")
}

func (t *PairScoringInputClassView) PropertyUser2() (ClassPropertyView, error) {
	return t.inner.Property("user2")
}

func (t *PairScoringInputClassView) PropertyUser1_sections() (ClassPropertyView, error) {
	return t.inner.Property("user1_sections")
}

func (t *PairScoringInputClassView) PropertyUser2_sections() (ClassPropertyView, error) {
	return t.inner.Property("user2_sections")
}

func (t *TypeBuilder) PairScoringInput() (*PairScoringInputClassView, error) {
	bld, err := t.inner.Class("PairScoringInput")
	if err != nil {
		return nil, err
	}
	return &PairScoringInputClassView{inner: bld}, nil
}

func (t *PairScoringInputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ProfileSectionsClassView struct {
	inner baml.ClassBuilder
}

func (t *ProfileSectionsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ProfileSectionsClassView) PropertySkills() (ClassPropertyView, error) {
	return t.inner.Property("skills")
}

func (t *ProfileSectionsClassView) PropertyVision() (ClassPropertyView, error) {
	return t.inner.Property("vision")
}

func (t *ProfileSectionsClassView) PropertyProject() (ClassPropertyView, error) {
	return t.inner.Property("project")
}

func (t *ProfileSectionsClassView) PropertyNeeds() (ClassPropertyView, error) {
	return t.inner.Property("needs")
}

func (t *TypeBuilder) ProfileSections() (*ProfileSectionsClassView, error) {
	bld, err := t.inner.Class("ProfileSections")
	if err != nil {
		return nil, err
	}
	return &ProfileSectionsClassView{inner: bld}, nil
}

func (t *ProfileSectionsClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
