// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/Cloudbird-Software/mutual/baml_client/baml_client/stream_types"
	"github.com/Cloudbird-Software/mutual/baml_client/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type stream struct{}

var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
	IsError   bool
	Error     error
	IsFinal   bool
	as_final  *TFinal
	as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() *TFinal {
	return s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() *TStream {
	return s.as_stream
}

// / Streaming version of DraftIntroduction
func (*stream) DraftIntroduction(ctx context.Context, user1_name string, user1_sections string, user2_name string, user2_sections string, instruction string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.IntroductionDraft, types.IntroductionDraft], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"user1_name": user1_name, "user1_sections": user1_sections, "user2_name": user2_name, "user2_sections": user2_sections, "instruction": instruction},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DraftIntroduction: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "DraftIntroduction", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.IntroductionDraft, types.IntroductionDraft])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.IntroductionDraft, types.IntroductionDraft]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.IntroductionDraft)
				channel <- StreamValue[stream_types.IntroductionDraft, types.IntroductionDraft]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.IntroductionDraft)
				channel <- StreamValue[stream_types.IntroductionDraft, types.IntroductionDraft]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of ExtractProfile
func (*stream) ExtractProfile(ctx context.Context, raw_text string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.ProfileSections, types.ProfileSections], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"raw_text": raw_text},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ExtractProfile: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "ExtractProfile", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.ProfileSections, types.ProfileSections])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.ProfileSections, types.ProfileSections]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.ProfileSections)
				channel <- StreamValue[stream_types.ProfileSections, types.ProfileSections]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.ProfileSections)
				channel <- StreamValue[stream_types.ProfileSections, types.ProfileSections]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GenerateHypothetical
func (*stream) GenerateHypothetical(ctx context.Context, section_name string, section_content string, n_descriptors int64, opts ...CallOptionFunc) (<-chan StreamValue[[]string, []string], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"section_name": section_name, "section_content": section_content, "n_descriptors": n_descriptors},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateHypothetical: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateHypothetical", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[[]string, []string])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[[]string, []string]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).([]string)
				channel <- StreamValue[[]string, []string]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).([]string)
				channel <- StreamValue[[]string, []string]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of ScorePairs
func (*stream) ScorePairs(ctx context.Context, pairs []types.PairScoringInput, instruction string, opts ...CallOptionFunc) (<-chan StreamValue[[]stream_types.DirectionalPairScore, []types.DirectionalPairScore], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"pairs": pairs, "instruction": instruction},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ScorePairs: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "ScorePairs", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[[]stream_types.DirectionalPairScore, []types.DirectionalPairScore])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[[]stream_types.DirectionalPairScore, []types.DirectionalPairScore]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).([]types.DirectionalPairScore)
				channel <- StreamValue[[]stream_types.DirectionalPairScore, []types.DirectionalPairScore]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).([]stream_types.DirectionalPairScore)
				channel <- StreamValue[[]stream_types.DirectionalPairScore, []types.DirectionalPairScore]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}
