// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/Cloudbird-Software/mutual/baml_client/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type build_request_stream struct{}

var StreamRequest = &build_request_stream{}

// Build streaming HTTP request for DraftIntroduction (returns baml.HTTPRequest)
func (*build_request_stream) DraftIntroduction(user1_name string, user1_sections string, user2_name string, user2_sections string, instruction string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"user1_name": user1_name, "user1_sections": user1_sections, "user2_name": user2_name, "user2_sections": user2_sections, "instruction": instruction, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DraftIntroduction: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "DraftIntroduction", encoded)
}

// Build streaming HTTP request for ExtractProfile (returns baml.HTTPRequest)
func (*build_request_stream) ExtractProfile(raw_text string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"raw_text": raw_text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ExtractProfile: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "ExtractProfile", encoded)
}

// Build streaming HTTP request for GenerateHypothetical (returns baml.HTTPRequest)
func (*build_request_stream) GenerateHypothetical(section_name string, section_content string, n_descriptors int64, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"section_name": section_name, "section_content": section_content, "n_descriptors": n_descriptors, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateHypothetical: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "GenerateHypothetical", encoded)
}

// Build streaming HTTP request for ScorePairs (returns baml.HTTPRequest)
func (*build_request_stream) ScorePairs(pairs []types.PairScoringInput, instruction string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"pairs": pairs, "instruction": instruction, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ScorePairs: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "ScorePairs", encoded)
}
