// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/Cloudbird-Software/mutual/baml_client/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

func DraftIntroduction(ctx context.Context, user1_name string, user1_sections string, user2_name string, user2_sections string, instruction string, opts ...CallOptionFunc) (types.IntroductionDraft, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"user1_name": user1_name, "user1_sections": user1_sections, "user2_name": user2_name, "user2_sections": user2_sections, "instruction": instruction},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "DraftIntroduction", encoded, callOpts.onTick)
		if err != nil {
			return types.IntroductionDraft{}, err
		}

		if result.Error != nil {
			return types.IntroductionDraft{}, result.Error
		}

		casted := (result.Data).(types.IntroductionDraft)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "DraftIntroduction", encoded, callOpts.onTick)
		if err != nil {
			return types.IntroductionDraft{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.IntroductionDraft{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.IntroductionDraft), nil
			}
		}

		return types.IntroductionDraft{}, fmt.Errorf("No data returned from stream")
	}
}

func ExtractProfile(ctx context.Context, raw_text string, opts ...CallOptionFunc) (types.ProfileSections, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"raw_text": raw_text},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "ExtractProfile", encoded, callOpts.onTick)
		if err != nil {
			return types.ProfileSections{}, err
		}

		if result.Error != nil {
			return types.ProfileSections{}, result.Error
		}

		casted := (result.Data).(types.ProfileSections)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "ExtractProfile", encoded, callOpts.onTick)
		if err != nil {
			return types.ProfileSections{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.ProfileSections{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.ProfileSections), nil
			}
		}

		return types.ProfileSections{}, fmt.Errorf("No data returned from stream")
	}
}

func GenerateHypothetical(ctx context.Context, section_name string, section_content string, n_descriptors int64, opts ...CallOptionFunc) ([]string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"section_name": section_name, "section_content": section_content, "n_descriptors": n_descriptors},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateHypothetical", encoded, callOpts.onTick)
		if err != nil {
			return nil, err
		}

		if result.Error != nil {
			return nil, result.Error
		}

		casted := (result.Data).([]string)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateHypothetical", encoded, callOpts.onTick)
		if err != nil {
			return nil, err
		}

		for result := range channel {
			if result.Error != nil {
				return nil, result.Error
			}

			if result.HasData {
				return result.Data.([]string), nil
			}
		}

		return nil, fmt.Errorf("No data returned from stream")
	}
}

func ScorePairs(ctx context.Context, pairs []types.PairScoringInput, instruction string, opts ...CallOptionFunc) ([]types.DirectionalPairScore, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"pairs": pairs, "instruction": instruction},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "ScorePairs", encoded, callOpts.onTick)
		if err != nil {
			return nil, err
		}

		if result.Error != nil {
			return nil, result.Error
		}

		casted := (result.Data).([]types.DirectionalPairScore)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "ScorePairs", encoded, callOpts.onTick)
		if err != nil {
			return nil, err
		}

		for result := range channel {
			if result.Error != nil {
				return nil, result.Error
			}

			if result.HasData {
				return result.Data.([]types.DirectionalPairScore), nil
			}
		}

		return nil, fmt.Errorf("No data returned from stream")
	}
}
