// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/Cloudbird-Software/mutual/baml_client/baml_client/stream_types"
	"github.com/Cloudbird-Software/mutual/baml_client/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.DirectionalPairScore":        reflect.TypeOf(types.DirectionalPairScore{}),
	"STREAM_TYPES.DirectionalPairScore": reflect.TypeOf(stream_types.DirectionalPairScore{}),
	"TYPES.IntroductionDraft":           reflect.TypeOf(types.IntroductionDraft{}),
	"STREAM_TYPES.IntroductionDraft":    reflect.TypeOf(stream_types.IntroductionDraft{}),
	"TYPES.PairScoringInput":            reflect.TypeOf(types.PairScoringInput{}),
	"STREAM_TYPES.PairScoringInput":     reflect.TypeOf(stream_types.PairScoringInput{}),
	"TYPES.ProfileSections":             reflect.TypeOf(types.ProfileSections{}),
	"STREAM_TYPES.ProfileSections":      reflect.TypeOf(stream_types.ProfileSections{}),
}
