// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type DirectionalPairScore struct {
	User1     *string  `json:"user1"`
	User2     *string  `json:"user2"`
	A_to_b    *float64 `json:"a_to_b"`
	B_to_a    *float64 `json:"b_to_a"`
	Reasoning *string  `json:"reasoning"`
}

func (c *DirectionalPairScore) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "DirectionalPairScore" {
		panic(fmt.Sprintf("expected DirectionalPairScore, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "user1":
			c.User1 = baml.Decode(valueHolder).Interface().(*string)

		case "user2":
			c.User2 = baml.Decode(valueHolder).Interface().(*string)

		case "a_to_b":
			c.A_to_b = baml.Decode(valueHolder).Interface().(*float64)

		case "b_to_a":
			c.B_to_a = baml.Decode(valueHolder).Interface().(*float64)

		case "reasoning":
			c.Reasoning = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class DirectionalPairScore", key))

		}
	}

}

func (c DirectionalPairScore) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["user1"] = c.User1

	fields["user2"] = c.User2

	fields["a_to_b"] = c.A_to_b

	fields["b_to_a"] = c.B_to_a

	fields["reasoning"] = c.Reasoning

	return baml.EncodeClass("DirectionalPairScore", fields, nil)
}

func (c DirectionalPairScore) BamlTypeName() string {
	return "DirectionalPairScore"
}

type IntroductionDraft struct {
	Intro          *string `json:"intro"`
	Starter_topics *string `json:"starter_topics"`
}

func (c *IntroductionDraft) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "IntroductionDraft" {
		panic(fmt.Sprintf("expected IntroductionDraft, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "intro":
			c.Intro = baml.Decode(valueHolder).Interface().(*string)

		case "starter_topics":
			c.Starter_topics = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class IntroductionDraft", key))

		}
	}

}

func (c IntroductionDraft) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["intro"] = c.Intro

	fields["starter_topics"] = c.Starter_topics

	return baml.EncodeClass("IntroductionDraft", fields, nil)
}

func (c IntroductionDraft) BamlTypeName() string {
	return "IntroductionDraft"
}

type PairScoringInput struct {
	User1          *string `json:"user1"`
	User2          *string `json:"user2"`
	User1_sections *string `json:"user1_sections"`
	User2_sections *string `json:"user2_sections"`
}

func (c *PairScoringInput) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "PairScoringInput" {
		panic(fmt.Sprintf("expected PairScoringInput, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "user1":
			c.User1 = baml.Decode(valueHolder).Interface().(*string)

		case "user2":
			c.User2 = baml.Decode(valueHolder).Interface().(*string)

		case "user1_sections":
			c.User1_sections = baml.Decode(valueHolder).Interface().(*string)

		case "user2_sections":
			c.User2_sections = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class PairScoringInput", key))

		}
	}

}

func (c PairScoringInput) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["user1"] = c.User1

	fields["user2"] = c.User2

	fields["user1_sections"] = c.User1_sections

	fields["user2_sections"] = c.User2_sections

	return baml.EncodeClass("PairScoringInput", fields, nil)
}

func (c PairScoringInput) BamlTypeName() string {
	return "PairScoringInput"
}

type ProfileSections struct {
	Skills  *string `json:"skills"`
	Vision  *string `json:"vision"`
	Project *string `json:"project"`
	Needs   *string `json:"needs"`
}

func (c *ProfileSections) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ProfileSections" {
		panic(fmt.Sprintf("expected ProfileSections, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "skills":
			c.Skills = baml.Decode(valueHolder).Interface().(*string)

		case "vision":
			c.Vision = baml.Decode(valueHolder).Interface().(*string)

		case "project":
			c.Project = baml.Decode(valueHolder).Interface().(*string)

		case "needs":
			c.Needs = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ProfileSections", key))

		}
	}

}

func (c ProfileSections) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["skills"] = c.Skills

	fields["vision"] = c.Vision

	fields["project"] = c.Project

	fields["needs"] = c.Needs

	return baml.EncodeClass("ProfileSections", fields, nil)
}

func (c ProfileSections) BamlTypeName() string {
	return "ProfileSections"
}
